---
- hosts: aws_ec2
  become: true

  tasks:

    - name: include variables
      include_vars: 'variables.yml'

    - name: update apt cache
      apt: update_cache=yes

    - name: install required packages
      apt:
        update_cache: yes
        pkg:
          - nginx
          - python3
          - python3-dev
          - python3-pip
          - python-setuptools

    - name: ensure nginx is running
      service: name=nginx state=started enabled=yes

    - name: clone repository
      git:
        repo: "{{ github_repo_url }}"
        dest: "{{ code_dest }}"

    - name: install virtualenv
      pip:
        name: virtualenv

    - name: check if virtual environment exists
      stat:
        path: "{{ virtualenv_path }}"
      register: virtualenv_exists

    - name: create virtual environment
      shell: virtualenv -p python3 {{ virtualenv_path|quote }}
      when: virtualenv_exists.stat.exists == False

    - name: install app requirements
      pip:
        requirements: "{{ code_dest }}/requirements.txt"
        virtualenv: "{{ virtualenv_path }}"
        extra_args: "--no-cache-dir"

    - name: copy nginx configuration
      template: src=nginx.conf.tpl dest=/etc/nginx/sites-available/objclf.conf
      notify:
        - restart nginx

    - name: create symlink in sites-enabled folder
      file: src=/etc/nginx/sites-available/objclf.conf dest=/etc/nginx/sites-enabled/objclf.conf state=link

    - name: copy systemd unit file to start uwsgi server
      template: src=objclf.service.tmp dest=/etc/systemd/system/objclf.service

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted